apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qeetmart
resources:
  - namespace.yaml
  - shared-config.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - user-service.yaml
  - product-service.yaml
  - inventory-service.yaml
  - ingress.yaml
