apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qeetmart.fullname" . }}-shared-config
  labels:
    {{- include "qeetmart.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.global.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qeetmart.fullname" . }}-shared-secrets
  labels:
    {{- include "qeetmart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.global.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
