{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "qeetmart.serviceName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "qeetmart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name | kebabcase }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "qeetmart.serviceName" (dict "root" $ "name" $name) }}
  minReplicas: {{ $svc.autoscaling.minReplicas }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.autoscaling.targetCPUUtilizationPercentage }}
---
{{- end }}
{{- end }}
