{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qeetmart.serviceName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "qeetmart.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name | kebabcase }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: {{ $name | kebabcase }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - name: http
      port: {{ $svc.servicePort }}
      targetPort: http
---
{{- end }}
{{- end }}
