apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qeetmart-prod
resources:
  - ../../base
patches:
  - path: replicas-patch.yaml
images:
  - name: ghcr.io/qeetgroup/qeetmart/api-gateway
    newTag: prod
  - name: ghcr.io/qeetgroup/qeetmart/auth-service
    newTag: prod
  - name: ghcr.io/qeetgroup/qeetmart/user-service
    newTag: prod
  - name: ghcr.io/qeetgroup/qeetmart/product-service
    newTag: prod
  - name: ghcr.io/qeetgroup/qeetmart/inventory-service
    newTag: prod
